- 1_Clases/cancion_favorita.txt
He creado una cacion que es mi favorita
> Creacion archivo Cancion

- README.md
Se ha agregado el nombre de los líderes de los equipos
> #4  Modified_table

- 1_Clases/Clase_3/PythonIntro_v1.ipynb
> #15 clase_3

- 1_Clases/Clase_3/.ipynb_checkpoints/PythonIntro_v1-checkpoint.ipynb
- 1_Clases/Clase_3/PythonIntro_v1.ipynb
> #15 actualización

- 1_Clases/Clase_3/PythonIntro_v1.ipynb
- 1_Clases/Clase_3/tarea/GRUPO_4.ipynb
- 1_Clases/Untitled.ipynb
Desarrollo de la pregunta 1 y 2.
> #25 Pregunta_1y2

- 1_Clases/Clase_3/.ipynb_checkpoints/PythonIntro_v1-checkpoint.ipynb
- 1_Clases/Clase_3/PythonIntro_v1.ipynb
- 1_Clases/Clase_3/tarea/.ipynb_checkpoints/GRUPO_4-checkpoint.ipynb
- 1_Clases/Clase_3/tarea/GRUPO_4.ipynb
> #25 Pregunta_3

- 1_Clases/Clase_3/tarea/.ipynb_checkpoints/GRUPO_1-checkpoint.ipynb
- 1_Clases/Clase_3/tarea/GRUPO_1.ipynb
Me encargué de resolver la pregunta 5. Agregué mi nombre, la pregunta y su solución al script "Grupo_1" de Jupyter.
> #30  Jason Cruz (5)

- 1_Clases/Clase_3/tarea/GRUPO_3.ipynb
> #28 RESPUESTA MIGUEL

- 1_Clases/Clase_3/tarea/GRUPO_3.ipynb
Ya completé la respuesta 3, continúa César
> #28 Respuesta_3

- 1_Clases/Clase_3/PythonIntro_v1.ipynb
Se actualizó el archivo de la clase numero 3.
> #15 Clases

- 1_Clases/Clase_3/tarea/GRUPO_4.ipynb
He realizado la tarea 2 de la pregunta 4
> #25 pregunta 4

- 1_Clases/Clase_3/tarea/.ipynb_checkpoints/Untitled-checkpoint.ipynb
- 1_Clases/Clase_3/tarea/GRUPO_1.ipynb
- 1_Clases/Clase_3/tarea/Untitled.ipynb
> #30 Cambios Jackeline

- 1_Clases/Clase_3/tarea/GRUPO_1.ipynb
Cambios finales, el documento está listo para la exposición.
> #30 Cambios finales

- 1_Clases/Clase_3/tarea/GRUPO_3.ipynb
Ya respondí la pregunta 6, sigue Gerson.
> #28 Respuesta6

- 1_Clases/Clase_4/Clase_4.ipynb
La clase  de creación de arrays
> #43 Class_4

- 1_Clases/Clase_4/Tarea/TAREA_4.ipynb
He agregado la tarea número 4 acerca de manejo de métodos en numpys
> #43 Tarea_numpys

- 1_Clases/Clase_4/Tarea/.ipynb_checkpoints/Prueba-checkpoint.ipynb
- 1_Clases/Clase_4/Tarea/Prueba.ipynb
Hicimos una prueba del uso de github.
> #43 Prueba_tarea

- 1_Clases/Clase_4/Tarea/Grupo1/.ipynb_checkpoints/Tarea4_JasonCruz-checkpoint.ipynb
- 1_Clases/Clase_4/Tarea/Grupo1/Tarea4_JasonCruz.ipynb
Disculpen Grupo 4 que me cole en su issue.
Finalmente se puede encontrar mi código de la tarea 4 en la carpeta del Grupo 1 en la dirección: "
The_Code_Blinders/1_Clases/Clase_4/Tarea/Grupo1/Tarea4_JasonCruz"
> #48 Jason Cruz

- 1_Clases/Clase_4/Tarea/GRUPO 3/.ipynb_checkpoints/GRUPO_3_BETSY_LAINES-checkpoint.ipynb
- 1_Clases/Clase_4/Tarea/GRUPO 3/GRUPO_3_BETSY_LAINES.ipynb
Ejercicios resueltos, continúa César
> #52 Ejercicios Betsy

- 1_Clases/Clase_4/Tarea/GRUPO 3/GRUPO_3_ GERSON CORNEJO.ipynb
Incluyo mi solucion de la tarea
> #52 HW_GCornejo

- Grupo_2/Mi_Cancion.txt
- Grupo_2/Tarea_2/.ipynb_checkpoints/Tarea_2-checkpoint.ipynb
- Grupo_2/Tarea_2/Tarea_2-checkpoint.ipynb
- Grupo_2/Tarea_3/.ipynb_checkpoints/Grupo2_Tarea_3-checkpoint.ipynb
- Grupo_2/Tarea_3/Grupo2_Tarea_3.ipynb
Hola @anzonyqr adjunto la solución de la tarea 3 en una carpeta llamada grupo 2.
> #58 Tarea 3 grupo 2 

- 1_Clases/Clase_9/.ipynb_checkpoints/clase_8-checkpoint.ipynb
- 1_Clases/Clase_9/clase_8.ipynb
> #68 Clase_final_pandas
